services:
  kiosk-crawl:
    image: ksieon/kiosk-crawl:latest
    expose:
      - "8000"
    container_name: kiosk-crawl
    env_file:
      - .env.prod
    environment:
      - ENV=prod
    networks:
      - kiosk-network

networks:
  kiosk-network:
    name: docker_kiosk-network
    external: true