services:
  kiosk-crawl:
    image: ksieon/kiosk-crawl:latest
    expose:
      - "8000"
    container_name: kiosk-crawl
    networks:
      - kiosk-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  kiosk-network:
    name: docker_kiosk-network
    external: true