name: build and deploy crawl service
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_ACTION_TOKEN }}
      
      - name: Deploy on server
        env:
          ENV_PROD: ${{ secrets.ENV_PROD }}
        run: |
            cd /home/ubuntu/actions-runner-crawl/_work/kiosk-be-crawl/kiosk-be-crawl
            echo "$ENV_PROD" > ./docker/.env.prod
            docker compose -f docker/docker-compose.yml down
            docker compose -f docker/docker-compose.yml pull
            docker compose -f docker/docker-compose.yml up -d
