name: build and deploy crawl service
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_ACTION_TOKEN }}

      - name: Build and push Docker image
        run: docker buildx build -f ./docker/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} --push .
  
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_PROD }}
          port: ${{ secrets.SSH_PORT_PROD }}
          username: ${{ secrets.SSH_USERNAME_PROD }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          script: |
            cd /home/ubuntu/actions-runner-crawl/_work/kiosk-be-crawl/kiosk-be-crawl
            docker-compose -f docker/docker-compose.yml down
            docker-compose -f docker/docker-compose.yml pull
            docker-compose -f docker/docker-compose.yml up -d
