name: build and deploy crawl service
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker build
        run: |
          cd /home/runner/work/kiosk-be-crawl/kiosk-be-crawl
          docker buildx build -f ./docker/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} --push .


  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Deploy on server
        env:
          ENV_PROD: ${{ secrets.ENV_PROD }}
        run: |
            cd /home/ubuntu/actions-runner-crawl/_work/kiosk-be-crawl/kiosk-be-crawl
            echo "$ENV_PROD" > ./docker/.env.prod
            docker compose -f docker/docker-compose.yml down
            docker compose -f docker/docker-compose.yml pull
            docker compose -f docker/docker-compose.yml up -d